config/routes.rb
Rails.application.routes.draw do
  root 						         'static_pages#home'

  get 'help' 		        => 'static_pages#help'

  get 'about'			      => 'static_pages#about'
 
  get 'projects' 	      => 'static_pages#projects'

	get 'weather'         => 'weather#index'

	post 'weather'        => 'weather#index'

	get 'scraper'         => 'page_scraper#index'

	get 'scraper/show'    => 'page_scraper#show'

	post 'scraper/show'   => 'page_scraper#show'

	get 'scraper/reddit'  => 'page_scraper#reddit'

	post 'scraper/reddit' => 'page_scraper#reddit'
	
end

app/models/get_page.rb
class GetPage < ActiveRecord::Base

	attr_accessor :list

	require 'nokogiri'
	require 'open-uri'
	
	def get_page(link)
		doc = Nokogiri::HTML(open('http://reddpics.com/r/' + link.to_s)) 
		return doc
	end

	def initialize(link)
		page = get_page(link)
		the_list(page)
	end

	def the_list(page)
		
		link_list = {}
		page.css("#images li").each do |node|
			
			get_link = node.at_css('a')['href']
			good_link = get_link unless get_link.include? 'google' or get_link.include? 'reddit' or get_link.exclude? 'jpg'

			edit_title = node.at_css('h2 a').text
			no_want1 = edit_title.index('[')
			no_want2 = edit_title.index('(')
			if edit_title.include? '['
				title = edit_title[0...no_want1]
			elsif edit_title.include? '('
				title = edit_title[0...no_want2]
			else
				title = edit_title
			end
			link_list[title] = good_link unless link_list.include? good_link
		end


		self.list = link_list
	end

end

app/models/scraper.rb
class Scraper < ActiveRecord::Base
	attr_accessor :theTemperature, :tempUpdated, :icon, :weather_description, :dateFirst, :tempHighFirst, :tempLowFirst,
								:weatherTest, :error, :error_description, :city, :state

	def check_params_current(city, state)
		check_current_weather_hash = fetch_current_temperature(city, state)
		current_weather_response = check_current_weather_hash.parsed_response['response']
		if current_weather_response['error']
			self.error = current_weather_response['type']
			self.error_description = current_weather_response['description']
			good_params = [city = "Port Washington", state = "NY"]
			return good_params
		else
			good_params = [city, state]
			return good_params
		end
	end
	
	def check_params_10Day(city, state)
		check_forecast_hash = fetch_10DayForecast(city, state)
		current_weather_response = check_forecast_hash.parsed_response['response']
		if current_weather_response['error']
			self.error = current_weather_response['type']
			self.error_description = current_weather_response['description']
			good_params = [city = "Port Washington", state = "NY"]
			return good_params
		else
			good_params = [city, state]
			return good_params
		end
	end

	def fetch_current_temperature(city, state)
		city.sub! ' ', '_'
		HTTParty.get("http://api.wunderground.com/api/db1ec1e1328bd050/conditions/q/" + state.to_s + "/" + city.to_s + ".xml")
	end

	def fetch_10DayForecast(city, state)
		city.sub! ' ', '_'
		HTTParty.get("http://api.wunderground.com/api/db1ec1e1328bd050/forecast10day/q/" + state.to_s + "/" + city.to_s + ".xml")
	end

	def initialize(dparams)
		currentCity  = check_params_current(dparams[:city], dparams[:state])[0]
		currentState = check_params_current(dparams[:city], dparams[:state])[1]
		current_weather_hash = fetch_current_temperature(currentCity, currentState)
		current_weather(current_weather_hash, currentCity, currentState)
		forecast_hash = fetch_10DayForecast(check_params_10Day(dparams[:city], dparams[:state])[0],check_params_10Day(dparams[:city], dparams[:state])[1])
		forecast(forecast_hash)
	end

	def current_weather(cw, city, state)
		current 								 = cw.parsed_response['response']['current_observation']
		self.city 							 = city
		self.state				 			 = state
		self.theTemperature 		 = current['temp_f']
		self.tempUpdated 				 = current['observation_time']
		self.icon 							 = current['icon_url']
		self.weather_description = current['icon']
	end

	def forecast(fc)
		forecast_first 		 	= fc.parsed_response['response']['forecast']['simpleforecast']['forecastdays']['forecastday'][0]
		self.dateFirst 		  = forecast_first['date']['monthname'] + forecast_first['date']['day']
		self.tempHighFirst  = forecast_first['high']['fahrenheit']
		self.tempLowFirst  	= forecast_first['low']['fahrenheit']
		self.weatherTest    = fc.parsed_response['response']['forecast']['simpleforecast']['forecastdays']['forecastday']
	end

	private


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/page_scraper_controller.rb
class PageScraperController < ApplicationController

	def index
	end

	def show
		reddpics = check_link
		@reddpics_list = GetPage.new(reddpics)
	end
	


	private
		def check_link
			reddpics = params[:webpage]
			bad_link  = "wallpapers"
			if not reddpics.blank? and reddpics.match(/\A[a-z]+\z/i)
				@message = "Successful grab"
				return reddpics
			else
				@message = "Something isn't correct"
			end
			return bad_link
		end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  


  def home
  end

  def help
  end

  def about
  end


end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController

	def index
		location = get_location
		@scraper = Scraper.new(location)
	end

	private

		def get_location

			uloca = { :city => params[:city], :state => params[:state] }
			loca  = { :state => "NY", :city => "Port_Washington" }

			if uloca[:city].blank?
				return loca
			elsif uloca[:city].gsub(" ", "_").match(/\A[a-z_]+\z/i)
				@notice = "Weather location successful"
				return uloca
			else
				@notice = "Something isn't correct"
			end
			return loca
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_scraper_helper.rb
module PageScraperHelper
end

app/helpers/static_pages_helper.rb
require 'rubygems'
require 'nokogiri'
require 'open-uri'

module StaticPagesHelper

	def scraper
		
		doc = Nokogiri::HTML(open('http://www.example.com'))

		option = doc.css('h1')

		puts option

	end

end

app/helpers/weather_helper.rb
module WeatherHelper
	def us_states
		[
		['Alabama', 'AL'],
		['Alaska', 'AK'],
		['Arizona', 'AZ'],
		['Arkansas', 'AR'],
		['California', 'CA'],
		['Colorado', 'CO'],
		['Connecticut', 'CT'],
		['Delaware', 'DE'],
		['District of Columbia', 'DC'],
		['Florida', 'FL'],
		['Georgia', 'GA'],
		['Hawaii', 'HI'],
		['Idaho', 'ID'],
		['Illinois', 'IL'],
		['Indiana', 'IN'],
		['Iowa', 'IA'],
		['Kansas', 'KS'],
		['Kentucky', 'KY'],
		['Louisiana', 'LA'],
		['Maine', 'ME'],
		['Maryland', 'MD'],
		['Massachusetts', 'MA'],
		['Michigan', 'MI'],
		['Minnesota', 'MN'],
		['Mississippi', 'MS'],
		['Missouri', 'MO'],
		['Montana', 'MT'],
		['Nebraska', 'NE'],
		['Nevada', 'NV'],
		['New Hampshire', 'NH'],
		['New Jersey', 'NJ'],
		['New Mexico', 'NM'],
		['New York', 'NY'],
		['North Carolina', 'NC'],
		['North Dakota', 'ND'],
		['Ohio', 'OH'],
		['Oklahoma', 'OK'],
		['Oregon', 'OR'],
		['Pennsylvania', 'PA'],
		['Puerto Rico', 'PR'],
		['Rhode Island', 'RI'],
		['South Carolina', 'SC'],
		['South Dakota', 'SD'],
		['Tennessee', 'TN'],
		['Texas', 'TX'],
		['Utah', 'UT'],
		['Vermont', 'VT'],
		['Virginia', 'VA'],
		['Washington', 'WA'],
		['West Virginia', 'WV'],
		['Wisconsin', 'WI'],
		['Wyoming', 'WY']
		]
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">

	<small>
		This is my first site flying solo
	</small>
	<nav>
		<ul>
			<li><a href="https://twitter.com/Mattydevicce" class="btn btn-block btn-social btn-twitter">
			  <i class="fa fa-twitter"></i>
			</a></li>
			<li><a href="https://www.linkedin.com/pub/matthew-morrisey/42/a90/3b5" class="btn btn-block btn-social btn-linkedin">
			  <i class="fa fa-linkedin"></i></a></li>			
			<li><a href="https://github.com/mattydevicce" class="btn btn-block btn-social btn-github">
			  <i class="fa fa-github"></i></a></li>
		</ul>
	</nav>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">  
  <div class="container">
    <%= link_to "Matty", root_path, id: "logo" %>
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      
    	<span class="sr-only">Toggle navigation</span>

    	<span class="icon-bar"></span>
    	<span class="icon-bar"></span>
    	<span class="icon-bar"></span>

    </button>    
    <nav class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "About",  about_path %></li>
        <li class="dropdown">
        	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
        	Projects<b class="caret"></b></a>
        	<ul class="dropdown-menu">
        		<li><%= link_to "Over view", projects_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Weather report", weather_path %></li>
        		<li><%= link_to "Image scraper", scraper_path %></li>
                <li><a href="https://stark-cliffs-3379.herokuapp.com/">Twitter clone</a></li>
        	</ul>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= yield(:title) %> ~ Matty Devicce</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<%= yield %>	
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/page_scraper/index.html.erb
<div class="container">

	<h2>What reddpics subredit pic page would you like to scrape?</h2>
	<%= form_tag("/scraper/show") do %>
		<p>reddpics.com/r/ <%= text_field_tag :webpage %>
		<%= submit_tag("Get pics", class: "btn btn-default btn-xs") %></p>
	<% end %>

</div>

app/views/page_scraper/show.html.erb
<div class="container">
<% if @reddpics_list.present? %>
	 <h1>There doesnt seem to be anything here</h1>
<% else %>
	<h1><%= @message %></h1>
<% end %>
<table class="table table-bordered">
	<thead>
		<tr>
			<th>Link</th>
			<th>Title</th>
		</tr>
	</thead>
	<tbody>
		<% @reddpics_list.list.each { |title, link| %>
		<tr>
			<td><%= title %></td>
			<td><a href="<%= link %>"><%= link %></td>
		</tr>
		<% } %>
	</tbody>

</table>



</div>

app/views/static_pages/_random_page.html.erb
<p>The current temperature is <%= @scraper.theTemperature %></p>
<p>The high for today is: <%= @scraper.tempHighFirst %></p>
<p>The low for today is: <%= @scraper.tempLowFirst %></p>
<p><%= image_tag @scraper.icon %> <%= @scraper.weather_description %></p>
<small><%= @scraper.tempUpdated %></small>

<div class="loop_table_down">
	<table class="table table-bordered table-hover atable">
		<thead>
			<tr>
				<th>Date</th>
				<th>High</th>
				<th>Low</th>
				<th>Weather</th>
			</tr>	
		</thead>
		<tbody>
			<% @scraper.weatherTest.drop(1).each { |d| date=d['date'] %>
				<tr>
					<td><%= date['monthname'] %> <%= date['day'] %></td>
					<td><%= d['high']['fahrenheit'] %></td>
					<td><%= d['low']['fahrenheit'] %></td>
					<td><%= d['conditions'] %><%= image_tag d['icon_url'], :class => "style_image" %></td>
				</tr>
			<% } %>
		</tbody>
	</table>
</div>

<div id="loop_table_across">
	<table class='table table-bordered dtable'>
		<thead>
			<tr>
			<% @scraper.weatherTest.drop(1).each { |d| date=d['date'] %>
				<th><%= date['monthname']%>   <%= date['day'] %></th>
			<% } %>
			</tr>
		</thead>
		<tbody>
			<tr>
				<% @scraper.weatherTest.drop(1).each { |d| %>
				<td>
					High: <%= d['high']['fahrenheit'] %>	<br>
					Low:  <%= d['low']['fahrenheit'] %>   <br>
					Weather: <%= d['conditions'] %>				<br>
					<%= image_tag d['icon_url'], :class => "style_image_again" %>


				</td>
				<% } %>
			</tr>
		</tbody>
	</table>
</div>



		current_weather(current_weather_hash)
		forecast_hash = fetch_10DayForecast
		forecast(forecast_hash)

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h2>This is about the app</h2>

<p>When I figure it out, I will let you know!</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>This is the help page</h1>

<p>If you need to contact me, do it here at <a href="mailto:mattydevicce@gmail.com?Subject=Hello%20there%20good%20buddy" target="_top">Matt's email</a></p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	
	<h1>Home</h1>

	<h2>This will be filled in later, if you need help, visit me at the <b><%= link_to 'HELP', help_path %></b> page</h2>

	<h2>Here are various <%= link_to 'projects', projects_path %> I have been working on</h2>



</div>

app/views/static_pages/projects.html.erb
<h2>Here is an example of using my first API</h2>
<p><%= link_to "Weather", weather_path %><br>
<p><%= link_to "Page Scraper", scraper_path %></p>
<p><a href="https://stark-cliffs-3379.herokuapp.com/">Ruby on Rails tutorial by Michael Hartl</a>

app/views/weather/_search.html.erb
<%= form_tag("/weather", class: "search") do %>
	<% if @scraper.error.present? || @scraper.error_description.present? %>
		<p class="search error">Error: <%= flash[:notice]=@scraper.error %></p>
		<p class="search error">Error: <%= flash[:notice]=@scraper.error_description %></p>
	<% end %>

	<p class="search">City: <%= text_field_tag :city %></p>
	<p class="search">State: <%= select_tag(:state, options_for_select(us_states)) %></p>

	<%= submit_tag("Get weather", class: "btn btn-default btn-xs search") %>
<% end %>

app/views/weather/index.html.erb
<div class="container">
	<h1>First time using an API</h1>

	<div class="row">
		<div class="col-md-9 currentemp">
			<p class="citystate">Current weather for <%= @scraper.city.gsub("_", " ").titleize %>, <%= @scraper.state %></p>
			<p class="floatleft">The current temperature is <%= @scraper.theTemperature %></p>
			<p>The high for today is: <%= @scraper.tempHighFirst %></p>
			<p>The low for today is: <%= @scraper.tempLowFirst %></p>
			<p><%= image_tag @scraper.icon %> <%= @scraper.weather_description %></p>
			<small><%= @scraper.tempUpdated %></small>
		</div>
			<div class="col-md-3">
				<p class="search"><%= @notice %></p>
				<%= render 'search' %>

			</div>
		</div>

	</div>
	<div class="loop_table_down">
		<table class="table table-bordered table-hover atable">
			<thead>
				<tr>
					<th>Date</th>
					<th>High</th>
					<th>Low</th>
					<th>Weather</th>
				</tr>	
			</thead>
			<tbody>
				<% @scraper.weatherTest.drop(1).each { |d| date=d['date'] %>
					<tr>
						<td><%= date['monthname'] %> <%= date['day'] %></td>
						<td><%= d['high']['fahrenheit'] %></td>
						<td><%= d['low']['fahrenheit'] %></td>
						<td><%= d['conditions'] %><%= image_tag d['icon_url'], :class => "style_image" %></td>
					</tr>
				<% } %>
			</tbody>
		</table>
	</div>

	<div id="loop_table_across">
		<table class='table table-bordered dtable'>
			<thead>
				<tr>
				<% @scraper.weatherTest.drop(1).each { |d| date=d['date'] %>
					<th><%= date['monthname']%>   <%= date['day'] %></th>
				<% } %>
				</tr>
			</thead>
			<tbody>
				<tr>
					<% @scraper.weatherTest.drop(1).each { |d| %>
					<td>
						High: <%= d['high']['fahrenheit'] %>	<br>
						Low:  <%= d['low']['fahrenheit'] %>   <br>
						Weather: <%= d['conditions'] %>				<br>
						<%= image_tag d['icon_url'], :class => "style_image_again" %>


					</td>
					<% } %>
				</tr>
			</tbody>
		</table>
	</div>
</div>